<?php
// pages/settings.php
if (session_status() === PHP_SESSION_NONE)
    session_start();

require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/auth_helper.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/config/conn.php';

if (!AuthChecker::isLoggedIn()) {
    header('Location: /auth/login');
    exit;
}

// Only admins can access
if (AuthChecker::getUserRole() !== 'admin') {
    header('Location: /dashboard');
    exit;
}

// ── Load current settings from DB ─────────────────────────────────────────
// We store settings as key-value pairs in a `system_settings` table.
// If the table doesn't exist yet, we fall back to defaults gracefully.
$settings = [];
$defaults = [
    // Barangay profile
    'barangay_name'         => 'Barangay Gulod',
    'barangay_address'      => 'Novaliches, Quezon City',
    'barangay_contact'      => '',
    'barangay_email'        => '',
    'barangay_logo'         => '',

    // Report settings
    'report_left_logo'           => '',   // QC logo / left logo path
    'report_right_logo'          => '',   // Gulod seal / right logo path
    'report_republic_line'       => 'REPUBLIC OF THE PHILIPPINES',
    'report_barangay_line'       => 'BARANGAY GULOD',
    'report_address_line'        => 'VILLAFLOR VILLAGE, DISTRICT V, QUEZON CITY',
    'report_tel_line'            => 'Tel. No. 8366-3198',
    'report_punong_name'         => 'REY ALDRIN S. TOLENTINO',
    'report_punong_position'     => 'Punong Barangay',
    'report_officials'           => '[]',  // JSON array of {name, position}
    'report_secretary_name'      => 'MILA B. NARIO',
    'report_treasurer_name'      => 'LUNINGNING R. ARATAS',
    'report_sk_name'             => 'ALJOHN JAYZEL E. CLEMENTE, JMA',
    'report_signatory_name'      => '',
    'report_signatory_pos'       => 'Punong Barangay',
    'report_footer_note'         => 'This is an official document generated by the SafeChain Emergency Response System.',

    // System controls
    'force_resolve_hours'        => '6',
    'maintenance_mode'           => '0',
    'dashboard_banner'           => '',
    'dashboard_banner_type'      => 'info',   // info | warning | danger

    // Notification sound
    'notification_sound'         => '',       // relative path to uploaded audio file
    'notification_volume'        => '70',     // 0–100
    'notification_duration'      => '3',      // seconds
];

try {
    $result = $conn->query("SELECT setting_key, setting_value FROM system_settings");
    if ($result) {
        while ($row = $result->fetch_assoc()) {
            $settings[$row['setting_key']] = $row['setting_value'];
        }
    }
} catch (Exception $e) {
    // Table doesn't exist yet — use defaults
}

// Merge defaults for any missing keys
foreach ($defaults as $key => $val) {
    if (!isset($settings[$key])) $settings[$key] = $val;
}

function s(array $settings, string $key): string {
    return htmlspecialchars($settings[$key] ?? '', ENT_QUOTES);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SafeChain | Settings</title>
    <base href="../" />
    <link rel="stylesheet" href="assets/unicons/line.css" />
    <script src="assets/js/tailwind/tailwind.min.js"></script>
    <link href="assets/css/font.css" rel="stylesheet" />
    <link rel="stylesheet" href="assets/css/sidebar.css" />
    <link rel="stylesheet" href="assets/css/page-load-animation.css" />
    <link rel="stylesheet" href="assets/css/toast.css" />
    <link rel="icon" type="image/x-icon" href="assets/img/logo.png">
    <script>tailwind.config = { darkMode: ["class", '[data-theme="dark"]'] };</script>
    <style>
        :root { --brand: #27C291; --brand-dim: rgba(39,194,145,.12); }
        .brand { color: var(--brand); }
        .brand-bg { background: var(--brand); }

        /* Tab system */
        .settings-tab { transition: all .2s; }
        .settings-tab.active {
            background: var(--brand-dim);
            color: var(--brand);
            font-weight: 600;
        }
        .settings-tab:not(.active):hover {
            background: rgba(0,0,0,.04);
        }
        .dark .settings-tab:not(.active):hover { background: rgba(255,255,255,.05); }
        .tab-panel { display: none; }
        .tab-panel.active { display: block; }

        /* Input styles */
        .sc-input {
            width: 100%;
            padding: .5rem .75rem;
            border-radius: .75rem;
            border: 1.5px solid #e2e8f0;
            background: #fff;
            font-size: .8125rem;
            color: #1e293b;
            transition: border-color .2s, box-shadow .2s;
            outline: none;
        }
        .sc-input:focus {
            border-color: var(--brand);
            box-shadow: 0 0 0 3px rgba(39,194,145,.18);
        }
        .dark .sc-input {
            background: #262626;
            border-color: #404040;
            color: #e2e8f0;
        }
        .dark .sc-input:focus { border-color: var(--brand); }

        .sc-label {
            display: block;
            font-size: .75rem;
            font-weight: 600;
            color: #475569;
            margin-bottom: .375rem;
        }
        .dark .sc-label { color: #94a3b8; }

        /* Toggle */
        .toggle-track {
            width: 44px; height: 24px;
            border-radius: 12px;
            background: #e2e8f0;
            position: relative;
            cursor: pointer;
            transition: background .2s;
        }
        .toggle-track.on { background: var(--brand); }
        .dark .toggle-track { background: #404040; }
        .toggle-thumb {
            position: absolute;
            top: 3px; left: 3px;
            width: 18px; height: 18px;
            border-radius: 50%;
            background: #fff;
            transition: transform .2s;
            box-shadow: 0 1px 3px rgba(0,0,0,.2);
        }
        .toggle-track.on .toggle-thumb { transform: translateX(20px); }

        /* Logo upload zone */
        .upload-zone {
            border: 2px dashed #e2e8f0;
            border-radius: 1rem;
            cursor: pointer;
            transition: border-color .2s, background .2s;
        }
        .upload-zone:hover, .upload-zone.drag-over {
            border-color: var(--brand);
            background: var(--brand-dim);
        }
        .dark .upload-zone { border-color: #404040; }
        .dark .upload-zone:hover { border-color: var(--brand); }

        /* Save button */
        .save-btn {
            background: var(--brand);
            color: #fff;
            padding: .6rem 1.5rem;
            border-radius: .75rem;
            font-size: .8125rem;
            font-weight: 600;
            transition: opacity .2s, transform .1s;
            display: inline-flex;
            align-items: center;
            gap: .5rem;
        }
        .save-btn:hover { opacity: .9; }
        .save-btn:active { transform: scale(.97); }
        .save-btn:disabled { opacity: .6; cursor: not-allowed; }

        /* Section card */
        .settings-card {
            background: #fff;
            border: 1px solid #e2e8f0;
            border-radius: 1.25rem;
            padding: 1.5rem;
            margin-bottom: 1rem;
        }
        .dark .settings-card {
            background: #262626;
            border-color: #404040;
        }
        .settings-card-title {
            font-size: .8125rem;
            font-weight: 700;
            color: #1e293b;
            margin-bottom: 1.25rem;
            display: flex;
            align-items: center;
            gap: .5rem;
        }
        .dark .settings-card-title { color: #e2e8f0; }

        .field-row { display: grid; gap: 1rem; }
        .field-row.cols-2 { grid-template-columns: 1fr 1fr; }
        @media (max-width: 640px) { .field-row.cols-2 { grid-template-columns: 1fr; } }

        /* Banner type pills */
        .banner-pill {
            padding: .35rem .85rem;
            border-radius: 99px;
            font-size: .75rem;
            font-weight: 600;
            border: 1.5px solid transparent;
            cursor: pointer;
            transition: all .15s;
        }
        .banner-pill.active-info    { background: rgba(59,130,246,.12);  color: #3b82f6; border-color: #3b82f6; }
        .banner-pill.active-warning { background: rgba(245,158,11,.12);  color: #f59e0b; border-color: #f59e0b; }
        .banner-pill.active-danger  { background: rgba(239,68,68,.12);   color: #ef4444; border-color: #ef4444; }
        .banner-pill:not([class*="active"]) {
            background: #f1f5f9; color: #64748b;
        }
        .dark .banner-pill:not([class*="active"]) { background: #404040; color: #94a3b8; }

        /* Hint text */
        .sc-hint { font-size: .7rem; color: #94a3b8; margin-top: .3rem; line-height: 1.4; }

        /* Unsaved dot */
        #unsavedDot { display: none; }
        body.dirty #unsavedDot { display: inline-block; }

        /* Preview badge */
        .preview-badge {
            font-size: .65rem; font-weight: 700; letter-spacing: .05em;
            padding: .15rem .5rem; border-radius: 99px;
            background: var(--brand-dim); color: var(--brand);
            text-transform: uppercase;
        }

        /* Waveform animation */
        @keyframes soundWave {
            0%, 100% { height: 6px; }
            50%       { height: 20px; }
        }
        .waveform-bar {
            height: 6px;
            animation: soundWave 0.6s ease-in-out infinite;
        }

        /* Volume slider */
        input[type=range] { -webkit-appearance: none; appearance: none; }
        input[type=range]::-webkit-slider-thumb {
            -webkit-appearance: none;
            width: 16px; height: 16px;
            border-radius: 50%;
            background: #27C291;
            cursor: pointer;
            box-shadow: 0 1px 4px rgba(39,194,145,.4);
        }
        input[type=range]::-webkit-slider-runnable-track {
            height: 6px; border-radius: 3px;
            background: linear-gradient(to right, #27C291 var(--val, 70%), #e2e8f0 var(--val, 70%));
        }
        .dark input[type=range]::-webkit-slider-runnable-track {
            background: linear-gradient(to right, #27C291 var(--val, 70%), #404040 var(--val, 70%));
        }
    </style>
</head>

<body class="min-h-screen flex transition-all duration-300 dark:bg-neutral-900">
    <?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/sidebar.php'; ?>

    <main id="mainContent" class="transition-all duration-500 ease-in-out ml-[302px] flex-1 p-8 pb-20">

        <!-- Header -->
        <div class="mb-7 flex items-start justify-between gap-4">
            <div>
                <p class="text-xs text-slate-400 dark:text-slate-500 font-medium mb-1 flex items-center gap-1.5">
                    <span>Admin</span>
                    <i class="uil uil-angle-right text-sm"></i>
                    <span>Settings</span>
                </p>
                <h1 class="text-2xl font-bold text-slate-900 dark:text-slate-100 tracking-tight flex items-center gap-3">
                    Website Settings
                    <span id="unsavedDot" class="inline-block w-2 h-2 rounded-full bg-orange-400" title="Unsaved changes"></span>
                </h1>
                <p class="text-slate-500 dark:text-slate-400 text-sm mt-0.5">Configure system-wide options, barangay info, and report branding.</p>
            </div>
            <button id="globalSaveBtn" class="save-btn" onclick="saveCurrentTab()">
                <i class="uil uil-save text-base"></i>
                Save Changes
            </button>
        </div>

        <div class="flex gap-6">

            <!-- Sidebar tabs -->
            <div class="w-48 flex-shrink-0">
                <div class="bg-white dark:bg-neutral-800 border border-slate-200 dark:border-neutral-700 rounded-2xl p-2 sticky top-6">
                    <?php
                    $tabs = [
                        ['id'=>'barangay',  'icon'=>'uil-building',       'label'=>'Barangay'],
                        ['id'=>'reports',   'icon'=>'uil-file-alt',        'label'=>'Reports'],
                        ['id'=>'system',    'icon'=>'uil-cog',             'label'=>'System'],
                    ];
                    foreach ($tabs as $tab): ?>
                    <button onclick="switchTab('<?= $tab['id'] ?>')"
                        class="settings-tab w-full flex items-center gap-2.5 px-3 py-2.5 rounded-xl text-sm text-slate-600 dark:text-slate-400 mb-1 last:mb-0"
                        data-tab="<?= $tab['id'] ?>">
                        <i class="uil <?= $tab['icon'] ?> text-base"></i>
                        <?= $tab['label'] ?>
                    </button>
                    <?php endforeach; ?>
                </div>
            </div>

            <!-- Tab content -->
            <div class="flex-1 min-w-0">

                <!-- ══════════════════════════════════════
                     TAB: BARANGAY PROFILE
                ══════════════════════════════════════ -->
                <div class="tab-panel active" id="tab-barangay">

                    <!-- Logo -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-image brand"></i> Barangay Logo
                        </p>
                        <div class="flex gap-5 items-start">
                            <div id="logoPreviewWrap" class="w-20 h-20 rounded-2xl border-2 border-slate-200 dark:border-neutral-600 overflow-hidden flex items-center justify-center bg-slate-50 dark:bg-neutral-700 flex-shrink-0">
                                <?php if (!empty($settings['barangay_logo'])): ?>
                                    <img id="logoPreview" src="<?= s($settings, 'barangay_logo') ?>" class="w-full h-full object-contain" />
                                <?php else: ?>
                                    <i class="uil uil-image-slash text-2xl text-slate-300 dark:text-neutral-600" id="logoPlaceholder"></i>
                                    <img id="logoPreview" src="" class="w-full h-full object-contain hidden" />
                                <?php endif; ?>
                            </div>
                            <div class="flex-1">
                                <div class="upload-zone p-5 text-center" id="logoDropzone" onclick="document.getElementById('logoInput').click()">
                                    <i class="uil uil-cloud-upload text-2xl text-slate-300 dark:text-neutral-600 mb-1 block"></i>
                                    <p class="text-xs font-semibold text-slate-500 dark:text-slate-400">Click to upload logo</p>
                                    <p class="text-xs text-slate-400 dark:text-neutral-500 mt-0.5">PNG, SVG or WebP — max 2MB</p>
                                    <input type="file" id="logoInput" accept="image/*" class="hidden" onchange="handleLogoUpload(this)" />
                                </div>
                                <p class="sc-hint mt-2">Used as the barangay logo in generated PDF reports and on the dashboard header.</p>
                                <?php if (!empty($settings['barangay_logo'])): ?>
                                <button onclick="clearLogo()" class="mt-2 text-xs text-red-400 hover:text-red-500 font-medium flex items-center gap-1">
                                    <i class="uil uil-times-circle"></i> Remove logo
                                </button>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>

                    <!-- Basic info -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-map-marker brand"></i> Barangay Information
                        </p>
                        <div class="flex flex-col gap-4">
                            <div>
                                <label class="sc-label">Barangay Name</label>
                                <input type="text" class="sc-input" id="barangay_name"
                                    value="<?= s($settings, 'barangay_name') ?>"
                                    placeholder="e.g. Barangay Gulod" />
                            </div>
                            <div>
                                <label class="sc-label">Address</label>
                                <input type="text" class="sc-input" id="barangay_address"
                                    value="<?= s($settings, 'barangay_address') ?>"
                                    placeholder="e.g. Novaliches, Quezon City" />
                            </div>
                            <div class="field-row cols-2">
                                <div>
                                    <label class="sc-label">Contact Number</label>
                                    <input type="text" class="sc-input" id="barangay_contact"
                                        value="<?= s($settings, 'barangay_contact') ?>"
                                        placeholder="+63 2 1234 5678" />
                                </div>
                                <div>
                                    <label class="sc-label">Email Address</label>
                                    <input type="email" class="sc-input" id="barangay_email"
                                        value="<?= s($settings, 'barangay_email') ?>"
                                        placeholder="barangay@example.gov.ph" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="flex justify-end">
                        <button class="save-btn" onclick="saveTab('barangay')">
                            <i class="uil uil-save"></i> Save Barangay Info
                        </button>
                    </div>
                </div>

                <!-- ══════════════════════════════════════
                     TAB: REPORT SETTINGS
                ══════════════════════════════════════ -->
                <div class="tab-panel" id="tab-reports">

                    <!-- ── Report Logos ───────────────────────────────── -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-image brand"></i> Report Header Logos
                        </p>
                        <p class="sc-hint mb-4">Two logos appear on either side of the report header — the city/government logo on the left and the barangay seal on the right.</p>
                        <div class="grid grid-cols-2 gap-4">
                            <?php
                            $logoSlots = [
                                ['id'=>'report_left_logo',  'label'=>'Left Logo',  'hint'=>'e.g. Quezon City logo',   'key'=>'report_left_logo'],
                                ['id'=>'report_right_logo', 'label'=>'Right Logo', 'hint'=>'e.g. Barangay Gulod seal', 'key'=>'report_right_logo'],
                            ];
                            foreach ($logoSlots as $slot): ?>
                            <div>
                                <label class="sc-label"><?= $slot['label'] ?></label>
                                <div class="flex flex-col items-center gap-3">
                                    <div class="w-20 h-20 rounded-2xl border-2 border-slate-200 dark:border-neutral-600 overflow-hidden flex items-center justify-center bg-slate-50 dark:bg-neutral-700">
                                        <?php if (!empty($settings[$slot['key']])): ?>
                                            <img id="<?= $slot['id'] ?>_preview"
                                                src="<?= rtrim(BASE_URL,'/').'/'.ltrim(s($settings,$slot['key']),'/') ?>"
                                                class="w-full h-full object-contain" />
                                        <?php else: ?>
                                            <i class="uil uil-image-slash text-2xl text-slate-300 dark:text-neutral-600" id="<?= $slot['id'] ?>_placeholder"></i>
                                            <img id="<?= $slot['id'] ?>_preview" src="" class="w-full h-full object-contain hidden" />
                                        <?php endif; ?>
                                    </div>
                                    <div class="w-full upload-zone p-3 text-center"
                                        onclick="document.getElementById('<?= $slot['id'] ?>_input').click()">
                                        <i class="uil uil-cloud-upload text-lg text-slate-300 dark:text-neutral-600 block mb-0.5"></i>
                                        <p class="text-xs text-slate-400 dark:text-neutral-500"><?= $slot['hint'] ?></p>
                                        <input type="file" id="<?= $slot['id'] ?>_input" accept="image/*" class="hidden"
                                            onchange="handleReportLogoUpload(this, '<?= $slot['id'] ?>')" />
                                    </div>
                                    <?php if (!empty($settings[$slot['key']])): ?>
                                    <button onclick="clearReportLogo('<?= $slot['id'] ?>')"
                                        class="text-xs text-red-400 hover:text-red-500 font-medium flex items-center gap-1">
                                        <i class="uil uil-times-circle"></i> Remove
                                    </button>
                                    <?php endif; ?>
                                    <input type="hidden" id="<?= $slot['id'] ?>_cleared" value="0" />
                                </div>
                            </div>
                            <?php endforeach; ?>
                        </div>
                    </div>

                    <!-- ── Header Text ────────────────────────────────── -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-align-center brand"></i> Report Header Text
                        </p>
                        <div class="flex flex-col gap-3">
                            <div>
                                <label class="sc-label">Republic Line</label>
                                <input type="text" class="sc-input" id="report_republic_line"
                                    value="<?= s($settings, 'report_republic_line') ?>"
                                    placeholder="REPUBLIC OF THE PHILIPPINES"
                                    oninput="updateHeaderPreview()" />
                            </div>
                            <div>
                                <label class="sc-label">Barangay Name Line</label>
                                <input type="text" class="sc-input" id="report_barangay_line"
                                    value="<?= s($settings, 'report_barangay_line') ?>"
                                    placeholder="BARANGAY GULOD"
                                    oninput="updateHeaderPreview()" />
                            </div>
                            <div>
                                <label class="sc-label">Address Line</label>
                                <input type="text" class="sc-input" id="report_address_line"
                                    value="<?= s($settings, 'report_address_line') ?>"
                                    placeholder="VILLAFLOR VILLAGE, DISTRICT V, QUEZON CITY"
                                    oninput="updateHeaderPreview()" />
                            </div>
                            <div>
                                <label class="sc-label">Tel / Contact Line</label>
                                <input type="text" class="sc-input" id="report_tel_line"
                                    value="<?= s($settings, 'report_tel_line') ?>"
                                    placeholder="Tel. No. 8366-3198"
                                    oninput="updateHeaderPreview()" />
                            </div>
                        </div>
                    </div>

                    <!-- ── Live Header Preview ────────────────────────── -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-eye brand"></i> Header Preview
                            <span class="preview-badge ml-auto">Live</span>
                        </p>
                        <div id="reportHeaderPreview"
                            class="rounded-xl border border-slate-200 dark:border-neutral-700 bg-white dark:bg-neutral-900 p-4">
                            <div class="flex items-center justify-between gap-4">
                                <div class="w-16 h-16 flex-shrink-0 flex items-center justify-center">
                                    <?php if (!empty($settings['report_left_logo'])): ?>
                                    <img id="prev_left_logo" src="<?= rtrim(BASE_URL,'/').'/'.ltrim(s($settings,'report_left_logo'),'/') ?>" class="max-w-full max-h-full object-contain" />
                                    <?php else: ?>
                                    <div id="prev_left_logo" class="w-14 h-14 rounded bg-slate-100 dark:bg-neutral-700 flex items-center justify-center">
                                        <i class="uil uil-image text-slate-300 text-xl"></i>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                <div class="flex-1 text-center">
                                    <p id="prev_republic" class="text-xs font-bold text-slate-800 dark:text-slate-200 leading-tight"><?= s($settings,'report_republic_line') ?: 'REPUBLIC OF THE PHILIPPINES' ?></p>
                                    <p id="prev_brgy_line" class="text-sm font-extrabold text-slate-900 dark:text-slate-100 leading-tight mt-0.5"><?= s($settings,'report_barangay_line') ?: 'BARANGAY GULOD' ?></p>
                                    <p id="prev_address" class="text-xs text-slate-600 dark:text-slate-400 leading-tight mt-0.5"><?= s($settings,'report_address_line') ?: 'Address' ?></p>
                                    <p id="prev_tel" class="text-xs text-slate-500 dark:text-slate-500 italic leading-tight mt-0.5"><?= s($settings,'report_tel_line') ?: 'Tel. No.' ?></p>
                                </div>
                                <div class="w-16 h-16 flex-shrink-0 flex items-center justify-center">
                                    <?php if (!empty($settings['report_right_logo'])): ?>
                                    <img id="prev_right_logo" src="<?= rtrim(BASE_URL,'/').'/'.ltrim(s($settings,'report_right_logo'),'/') ?>" class="max-w-full max-h-full object-contain" />
                                    <?php else: ?>
                                    <div id="prev_right_logo" class="w-14 h-14 rounded bg-slate-100 dark:bg-neutral-700 flex items-center justify-center">
                                        <i class="uil uil-image text-slate-300 text-xl"></i>
                                    </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- ── Punong Barangay ────────────────────────────── -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-user-circle brand"></i> Punong Barangay
                        </p>
                        <div class="field-row cols-2">
                            <div>
                                <label class="sc-label">Full Name</label>
                                <input type="text" class="sc-input" id="report_punong_name"
                                    value="<?= s($settings, 'report_punong_name') ?>"
                                    placeholder="e.g. JUAN DELA CRUZ" />
                            </div>
                            <div>
                                <label class="sc-label">Position Label</label>
                                <input type="text" class="sc-input" id="report_punong_position"
                                    value="<?= s($settings, 'report_punong_position') ?>"
                                    placeholder="Punong Barangay" />
                            </div>
                        </div>
                    </div>

                    <!-- ── Kagawad List ───────────────────────────────── -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-users-alt brand"></i> Barangay Kagawad
                            <span class="ml-auto text-xs font-normal text-slate-400 dark:text-slate-500">Add up to 7</span>
                        </p>
                        <div id="kagawadList" class="flex flex-col gap-2 mb-3">
                            <?php
                            $officials = json_decode($settings['report_officials'] ?? '[]', true) ?: [];
                            foreach ($officials as $idx => $off): ?>
                            <div class="kagawad-row flex gap-2 items-center" data-index="<?= $idx ?>">
                                <input type="text" class="sc-input flex-1" placeholder="Full name (ALL CAPS)"
                                    value="<?= htmlspecialchars($off['name'] ?? '', ENT_QUOTES) ?>" />
                                <input type="text" class="sc-input w-40" placeholder="Position (optional)"
                                    value="<?= htmlspecialchars($off['position'] ?? '', ENT_QUOTES) ?>" />
                                <button type="button" onclick="removeKagawad(this)"
                                    class="w-8 h-8 flex-shrink-0 flex items-center justify-center rounded-lg text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 hover:text-red-500 transition-colors">
                                    <i class="uil uil-trash-alt text-base"></i>
                                </button>
                            </div>
                            <?php endforeach; ?>
                        </div>
                        <button type="button" onclick="addKagawad()"
                            class="flex items-center gap-2 text-xs font-semibold brand hover:opacity-80 transition-opacity">
                            <i class="uil uil-plus-circle text-base"></i> Add Kagawad
                        </button>
                    </div>

                    <!-- ── Other Officials ───────────────────────────── -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-medal brand"></i> Other Officials
                        </p>
                        <div class="flex flex-col gap-3">
                            <div class="field-row cols-2">
                                <div>
                                    <label class="sc-label">SK Chairperson Name</label>
                                    <input type="text" class="sc-input" id="report_sk_name"
                                        value="<?= s($settings, 'report_sk_name') ?>"
                                        placeholder="Full name" />
                                </div>
                                <div>
                                    <label class="sc-label">SK Position Label</label>
                                    <input type="text" class="sc-input" value="SK Chairperson" readonly
                                        class="sc-input opacity-60 cursor-not-allowed" />
                                </div>
                            </div>
                            <div class="field-row cols-2">
                                <div>
                                    <label class="sc-label">Barangay Secretary</label>
                                    <input type="text" class="sc-input" id="report_secretary_name"
                                        value="<?= s($settings, 'report_secretary_name') ?>"
                                        placeholder="Full name" />
                                </div>
                                <div>
                                    <label class="sc-label">Barangay Treasurer</label>
                                    <input type="text" class="sc-input" id="report_treasurer_name"
                                        value="<?= s($settings, 'report_treasurer_name') ?>"
                                        placeholder="Full name" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- ── Report Signatory & Footer ─────────────────── -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-pen brand"></i> Report Signatory & Footer
                        </p>
                        <div class="flex flex-col gap-3">
                            <div class="field-row cols-2">
                                <div>
                                    <label class="sc-label">Signatory Name</label>
                                    <input type="text" class="sc-input" id="report_signatory_name"
                                        value="<?= s($settings, 'report_signatory_name') ?>"
                                        placeholder="Who signs the generated report" />
                                    <p class="sc-hint">Printed below the signature line. Usually the Punong Barangay.</p>
                                </div>
                                <div>
                                    <label class="sc-label">Position / Title</label>
                                    <input type="text" class="sc-input" id="report_signatory_pos"
                                        value="<?= s($settings, 'report_signatory_pos') ?>"
                                        placeholder="e.g. Punong Barangay" />
                                </div>
                            </div>
                            <div>
                                <label class="sc-label">Report Footer Note</label>
                                <textarea class="sc-input" id="report_footer_note" rows="2"
                                    placeholder="Optional disclaimer printed at the bottom of every report"><?= s($settings, 'report_footer_note') ?></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="flex justify-end">
                        <button class="save-btn" onclick="saveTab('reports')">
                            <i class="uil uil-save"></i> Save Report Settings
                        </button>
                    </div>
                </div>

                <!-- ══════════════════════════════════════
                     TAB: SYSTEM CONTROLS
                ══════════════════════════════════════ -->
                <div class="tab-panel" id="tab-system">

                    <!-- Force resolve threshold -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-clock-eight brand"></i> Force-Resolve Threshold
                        </p>
                        <p class="text-xs text-slate-500 dark:text-slate-400 mb-4 leading-relaxed">
                            If an incident stays in <strong class="text-slate-700 dark:text-slate-300">Responding</strong> status for this many hours without being resolved by the responder, the Force Resolve button becomes available to admins.
                        </p>
                        <div class="flex items-center gap-4">
                            <div class="flex-1 max-w-xs">
                                <label class="sc-label">Threshold (hours)</label>
                                <div class="flex items-center gap-2">
                                    <input type="number" class="sc-input" id="force_resolve_hours"
                                        value="<?= s($settings, 'force_resolve_hours') ?>"
                                        min="1" max="48" step="1" style="max-width:100px" />
                                    <span class="text-sm text-slate-500 dark:text-slate-400">hours</span>
                                </div>
                                <p class="sc-hint">Recommended: 6 hours. Min: 1 hour, Max: 48 hours.</p>
                            </div>
                            <div class="flex-1 p-4 rounded-2xl bg-orange-50 dark:bg-orange-900/20 border border-orange-200 dark:border-orange-800/30">
                                <p class="text-xs font-semibold text-orange-700 dark:text-orange-300 flex items-center gap-1.5 mb-1">
                                    <i class="uil uil-exclamation-triangle"></i> How it works
                                </p>
                                <p class="text-xs text-orange-600 dark:text-orange-400 leading-relaxed">
                                    After the threshold, the admin can force-resolve with a reason. This is logged in the incident timeline for accountability.
                                </p>
                            </div>
                        </div>
                    </div>

                    <!-- Maintenance mode -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-constructor brand"></i> Maintenance Mode
                        </p>
                        <div class="flex items-start justify-between gap-6">
                            <div class="flex-1">
                                <p class="text-xs text-slate-500 dark:text-slate-400 leading-relaxed mb-2">
                                    When enabled, responders on the mobile app will see a maintenance notice and will be unable to submit new actions. Existing incidents remain visible. <strong class="text-slate-700 dark:text-slate-300">Use this during system updates or database maintenance.</strong>
                                </p>
                                <div class="p-3 rounded-xl bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800/30">
                                    <p class="text-xs text-red-600 dark:text-red-400 font-medium flex items-center gap-1.5">
                                        <i class="uil uil-exclamation-circle"></i>
                                        Enabling this will block all responder activity on the mobile app. Disable it as soon as maintenance is complete.
                                    </p>
                                </div>
                            </div>
                            <div class="flex-shrink-0 flex flex-col items-center gap-2">
                                <div class="toggle-track <?= $settings['maintenance_mode'] === '1' ? 'on' : '' ?>"
                                    id="maintenanceToggle"
                                    onclick="toggleSwitch('maintenanceToggle', 'maintenance_mode')">
                                    <div class="toggle-thumb"></div>
                                </div>
                                <span id="maintenanceLabel" class="text-xs font-semibold <?= $settings['maintenance_mode'] === '1' ? 'text-red-500' : 'text-slate-400 dark:text-slate-500' ?>">
                                    <?= $settings['maintenance_mode'] === '1' ? 'ON' : 'OFF' ?>
                                </span>
                                <input type="hidden" id="maintenance_mode" value="<?= s($settings, 'maintenance_mode') ?>" />
                            </div>
                        </div>
                    </div>

                    <!-- Dashboard banner -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-comment-info brand"></i> Dashboard Banner
                        </p>
                        <p class="text-xs text-slate-500 dark:text-slate-400 mb-4 leading-relaxed">
                            Shows a dismissable banner at the top of the admin dashboard. Leave blank to hide the banner.
                        </p>
                        <div class="flex flex-col gap-4">
                            <div>
                                <label class="sc-label">Banner Message</label>
                                <input type="text" class="sc-input" id="dashboard_banner"
                                    value="<?= s($settings, 'dashboard_banner') ?>"
                                    placeholder="e.g. System will undergo maintenance Saturday 10:00 PM" />
                            </div>
                            <div>
                                <label class="sc-label">Banner Type</label>
                                <div class="flex gap-2 flex-wrap" id="bannerTypePills">
                                    <button type="button" onclick="setBannerType('info')"
                                        class="banner-pill <?= $settings['dashboard_banner_type'] === 'info' ? 'active-info' : '' ?>"
                                        data-type="info">
                                        <i class="uil uil-info-circle mr-1"></i>Info
                                    </button>
                                    <button type="button" onclick="setBannerType('warning')"
                                        class="banner-pill <?= $settings['dashboard_banner_type'] === 'warning' ? 'active-warning' : '' ?>"
                                        data-type="warning">
                                        <i class="uil uil-exclamation-triangle mr-1"></i>Warning
                                    </button>
                                    <button type="button" onclick="setBannerType('danger')"
                                        class="banner-pill <?= $settings['dashboard_banner_type'] === 'danger' ? 'active-danger' : '' ?>"
                                        data-type="danger">
                                        <i class="uil uil-exclamation-circle mr-1"></i>Danger
                                    </button>
                                </div>
                                <input type="hidden" id="dashboard_banner_type" value="<?= s($settings, 'dashboard_banner_type') ?>" />
                            </div>

                            <!-- Banner preview -->
                            <div id="bannerPreviewWrap" class="<?= empty($settings['dashboard_banner']) ? 'hidden' : '' ?>">
                                <label class="sc-label flex items-center gap-2">
                                    Preview <span class="preview-badge">Preview</span>
                                </label>
                                <div id="bannerPreview" class="rounded-xl px-4 py-3 flex items-center gap-3 text-sm font-medium
                                    <?php
                                    echo match($settings['dashboard_banner_type']) {
                                        'warning' => 'bg-yellow-50 dark:bg-yellow-900/20 text-yellow-700 dark:text-yellow-300 border border-yellow-200 dark:border-yellow-800/30',
                                        'danger'  => 'bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-300 border border-red-200 dark:border-red-800/30',
                                        default   => 'bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 border border-blue-200 dark:border-blue-800/30',
                                    };
                                    ?>">
                                    <i id="bannerPreviewIcon" class="uil <?php
                                        echo match($settings['dashboard_banner_type']) {
                                            'warning' => 'uil-exclamation-triangle',
                                            'danger'  => 'uil-exclamation-circle',
                                            default   => 'uil-info-circle',
                                        };
                                    ?> text-lg flex-shrink-0"></i>
                                    <span id="bannerPreviewText"><?= s($settings, 'dashboard_banner') ?></span>
                                    <button class="ml-auto opacity-60 hover:opacity-100"><i class="uil uil-times"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Notification Sound -->
                    <div class="settings-card">
                        <p class="settings-card-title">
                            <i class="uil uil-bell brand"></i> Notification Sound
                        </p>
                        <p class="text-xs text-slate-500 dark:text-slate-400 mb-4 leading-relaxed">
                            The alert sound played on the admin dashboard whenever a new incident is reported. Upload a custom audio file or keep the default.
                        </p>

                        <!-- Current file + upload zone -->
                        <div class="flex gap-4 items-start mb-4">
                            <div class="w-14 h-14 rounded-2xl bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800/30 flex items-center justify-center flex-shrink-0">
                                <i class="uil uil-volume text-2xl brand" id="soundIcon"></i>
                            </div>
                            <div class="flex-1">
                                <!-- Current sound name -->
                                <p class="text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1" id="soundFileName">
                                    <?php
                                    if (!empty($settings['notification_sound'])) {
                                        echo htmlspecialchars(basename($settings['notification_sound']));
                                    } else {
                                        echo 'Default alert sound (alert.mp3)';
                                    }
                                    ?>
                                </p>
                                <div class="upload-zone p-4 text-center" onclick="document.getElementById('soundInput').click()">
                                    <i class="uil uil-cloud-upload text-xl text-slate-300 dark:text-neutral-600 mb-1 block"></i>
                                    <p class="text-xs font-semibold text-slate-500 dark:text-slate-400">Click to upload audio file</p>
                                    <p class="text-xs text-slate-400 dark:text-neutral-500 mt-0.5">MP3, WAV, or OGG — max 5MB</p>
                                    <input type="file" id="soundInput" accept="audio/mpeg,audio/wav,audio/ogg,audio/mp3,.mp3,.wav,.ogg"
                                        class="hidden" onchange="handleSoundUpload(this)" />
                                </div>
                                <?php if (!empty($settings['notification_sound'])): ?>
                                <button onclick="clearSound()" class="mt-2 text-xs text-red-400 hover:text-red-500 font-medium flex items-center gap-1">
                                    <i class="uil uil-times-circle"></i> Remove custom sound (revert to default)
                                </button>
                                <?php endif; ?>
                            </div>
                        </div>

                        <!-- Volume slider -->
                        <div class="mb-4">
                            <label class="sc-label flex items-center justify-between">
                                <span>Volume</span>
                                <span id="volumeDisplay" class="font-bold brand"><?= s($settings, 'notification_volume') ?>%</span>
                            </label>
                            <div class="flex items-center gap-3">
                                <i class="uil uil-volume-mute text-slate-400 dark:text-slate-500 text-lg flex-shrink-0"></i>
                                <input type="range" id="notification_volume" min="0" max="100" step="5"
                                    value="<?= s($settings, 'notification_volume') ?>"
                                    class="flex-1 accent-[#27C291] h-2 rounded-full cursor-pointer"
                                    oninput="document.getElementById('volumeDisplay').textContent = this.value + '%'; document.body.classList.add('dirty')" />
                                <i class="uil uil-volume text-slate-400 dark:text-slate-500 text-lg flex-shrink-0"></i>
                            </div>
                        </div>

                        <!-- Duration -->
                        <div class="mb-5">
                            <label class="sc-label">Play Duration</label>
                            <div class="flex items-center gap-2">
                                <input type="number" class="sc-input" id="notification_duration"
                                    value="<?= s($settings, 'notification_duration') ?>"
                                    min="1" max="30" step="1" style="max-width:90px" />
                                <span class="text-sm text-slate-500 dark:text-slate-400">seconds</span>
                            </div>
                            <p class="sc-hint">How long the sound plays before being cut off. Min: 1s, Max: 30s.</p>
                        </div>

                        <!-- Test button + waveform indicator -->
                        <div class="flex items-center gap-3">
                            <button type="button" id="testSoundBtn"
                                onclick="testNotificationSound()"
                                class="flex items-center gap-2 px-4 py-2 rounded-xl border border-slate-200 dark:border-neutral-600
                                    text-xs font-semibold text-slate-600 dark:text-slate-400
                                    hover:bg-slate-50 dark:hover:bg-neutral-700 transition-colors duration-150">
                                <i class="uil uil-play-circle text-base brand"></i>
                                Test Sound
                            </button>
                            <!-- Animated waveform bars (visible while playing) -->
                            <div id="soundWaveform" class="hidden items-center gap-0.5 h-5">
                                <?php for ($i = 0; $i < 5; $i++): ?>
                                <div class="w-1 rounded-full bg-[#27C291] waveform-bar" style="animation-delay: <?= $i * 0.1 ?>s"></div>
                                <?php endfor; ?>
                            </div>
                            <span id="soundStatus" class="text-xs text-slate-400 dark:text-slate-500 hidden">Playing…</span>
                        </div>

                        <!-- Hidden input to track if sound was cleared -->
                        <input type="hidden" id="notification_sound_cleared" value="0" />
                    </div>

                    <div class="flex justify-end">
                        <button class="save-btn" onclick="saveTab('system')">
                            <i class="uil uil-save"></i> Save System Settings
                        </button>
                    </div>

                </div>
            </div>
        </div>
    </main>

    <div id="toastContainer" class="fixed top-4 right-4 z-50 space-y-3 max-w-md w-full"></div>

    <script src="assets/js/sidebar.js"></script>
    <script src="assets/js/toast.js"></script>
    <script src="assets/js/modal.js"></script>
    <script>
    // ── Tab management ───────────────────────────────────────────────────
    function switchTab(id) {
        document.querySelectorAll('.tab-panel').forEach(p => p.classList.remove('active'));
        document.querySelectorAll('.settings-tab').forEach(b => b.classList.remove('active'));
        document.getElementById('tab-' + id).classList.add('active');
        document.querySelector(`.settings-tab[data-tab="${id}"]`).classList.add('active');
        // update global save btn label
        const labels = { barangay: 'Barangay Info', reports: 'Report Settings', system: 'System Settings' };
        document.getElementById('globalSaveBtn').innerHTML =
            `<i class="uil uil-save text-base"></i> Save ${labels[id]}`;
        currentTab = id;
    }
    let currentTab = 'barangay';

    function saveCurrentTab() { saveTab(currentTab); }

    // ── Dirty tracking ───────────────────────────────────────────────────
    document.querySelectorAll('.sc-input').forEach(el => {
        el.addEventListener('input', () => document.body.classList.add('dirty'));
    });

    // ── Logo upload ──────────────────────────────────────────────────────
    function handleLogoUpload(input) {
        const file = input.files[0];
        if (!file) return;
        if (file.size > 2 * 1024 * 1024) { showToast('Logo must be under 2MB', 'error'); return; }
        const reader = new FileReader();
        reader.onload = e => {
            const img = document.getElementById('logoPreview');
            const ph  = document.getElementById('logoPlaceholder');
            img.src = e.target.result;
            img.classList.remove('hidden');
            if (ph) ph.classList.add('hidden');
            document.body.classList.add('dirty');
        };
        reader.readAsDataURL(file);
    }

    function clearLogo() {
        document.getElementById('logoPreview').src = '';
        document.getElementById('logoPreview').classList.add('hidden');
        const ph = document.getElementById('logoPlaceholder');
        if (ph) ph.classList.remove('hidden');
        document.getElementById('logoInput').value = '';
        document.body.classList.add('dirty');
    }

    function handleSealUpload(input) {
        // legacy — replaced by handleReportLogoUpload
    }

    // ── Report logo uploads (left + right) ───────────────────────────────
    function handleReportLogoUpload(input, slotId) {
        const file = input.files[0];
        if (!file) return;
        if (file.size > 2 * 1024 * 1024) { showToast('Logo must be under 2MB', 'error'); input.value = ''; return; }
        const reader = new FileReader();
        reader.onload = e => {
            const img = document.getElementById(slotId + '_preview');
            const ph  = document.getElementById(slotId + '_placeholder');
            if (img) { img.src = e.target.result; img.classList.remove('hidden'); }
            if (ph)  ph.classList.add('hidden');
            // update live preview
            const side = slotId.includes('left') ? 'prev_left_logo' : 'prev_right_logo';
            const prevEl = document.getElementById(side);
            if (prevEl) {
                prevEl.outerHTML = `<img id="${side}" src="${e.target.result}" class="max-w-full max-h-full object-contain" style="max-height:64px" />`;
            }
            document.getElementById(slotId + '_cleared').value = '0';
            document.body.classList.add('dirty');
        };
        reader.readAsDataURL(file);
    }

    function clearReportLogo(slotId) {
        const img = document.getElementById(slotId + '_preview');
        const ph  = document.getElementById(slotId + '_placeholder');
        const inp = document.getElementById(slotId + '_input');
        if (img) { img.src = ''; img.classList.add('hidden'); }
        if (ph)  ph.classList.remove('hidden');
        if (inp) inp.value = '';
        document.getElementById(slotId + '_cleared').value = '1';
        // reset preview placeholder
        const side = slotId.includes('left') ? 'prev_left_logo' : 'prev_right_logo';
        const prevEl = document.getElementById(side);
        if (prevEl) {
            prevEl.outerHTML = `<div id="${side}" class="w-14 h-14 rounded bg-slate-100 dark:bg-neutral-700 flex items-center justify-center"><i class="uil uil-image text-slate-300 text-xl"></i></div>`;
        }
        document.body.classList.add('dirty');
    }

    // ── Live header preview ───────────────────────────────────────────────
    function updateHeaderPreview() {
        const map = {
            'report_republic_line': 'prev_republic',
            'report_barangay_line': 'prev_brgy_line',
            'report_address_line':  'prev_address',
            'report_tel_line':      'prev_tel',
        };
        for (const [inputId, previewId] of Object.entries(map)) {
            const inp = document.getElementById(inputId);
            const prv = document.getElementById(previewId);
            if (inp && prv) prv.textContent = inp.value || inp.placeholder;
        }
        document.body.classList.add('dirty');
    }

    // ── Kagawad rows ──────────────────────────────────────────────────────
    function addKagawad() {
        const list = document.getElementById('kagawadList');
        const rows = list.querySelectorAll('.kagawad-row');
        if (rows.length >= 7) { showToast('Maximum 7 Kagawad rows', 'error'); return; }
        const div = document.createElement('div');
        div.className = 'kagawad-row flex gap-2 items-center';
        div.innerHTML = `
            <input type="text" class="sc-input flex-1" placeholder="Full name (ALL CAPS)" />
            <input type="text" class="sc-input w-40" placeholder="Position (optional)" />
            <button type="button" onclick="removeKagawad(this)"
                class="w-8 h-8 flex-shrink-0 flex items-center justify-center rounded-lg text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 hover:text-red-500 transition-colors">
                <i class="uil uil-trash-alt text-base"></i>
            </button>`;
        list.appendChild(div);
        div.querySelector('input').focus();
        document.body.classList.add('dirty');
    }

    function removeKagawad(btn) {
        btn.closest('.kagawad-row').remove();
        document.body.classList.add('dirty');
    }

    function collectKagawad() {
        const rows = document.querySelectorAll('#kagawadList .kagawad-row');
        return JSON.stringify([...rows].map(row => {
            const inputs = row.querySelectorAll('input');
            return { name: inputs[0].value.trim(), position: inputs[1].value.trim() };
        }).filter(r => r.name));
    }

    // ── Save ─────────────────────────────────────────────────────────────
    async function saveTab(tab) {
        const btn = document.querySelector(`[onclick="saveTab('${tab}')"]`) ||
                    document.getElementById('globalSaveBtn');
        const orig = btn.innerHTML;
        btn.disabled = true;
        btn.innerHTML = `<i class="uil uil-spinner-alt animate-spin"></i> Saving…`;

        const fieldMaps = {
            barangay: ['barangay_name','barangay_address','barangay_contact','barangay_email'],
            reports:  ['report_republic_line','report_barangay_line','report_address_line','report_tel_line',
                       'report_punong_name','report_punong_position',
                       'report_sk_name','report_secretary_name','report_treasurer_name',
                       'report_signatory_name','report_signatory_pos','report_footer_note'],
            system:   ['force_resolve_hours','maintenance_mode','dashboard_banner','dashboard_banner_type',
                       'notification_volume','notification_duration','notification_sound_cleared'],
        };

        const payload = { tab };
        (fieldMaps[tab] || []).forEach(key => {
            const el = document.getElementById(key);
            if (el) payload[key] = el.value;
        });

        // Kagawad JSON
        if (tab === 'reports') {
            payload['report_officials'] = collectKagawad();
        }

        // File uploads — barangay tab
        if (tab === 'barangay') {
            const logoFile = document.getElementById('logoInput')?.files[0];
            if (logoFile) payload['barangay_logo_data'] = await fileToBase64(logoFile);
        }

        // File uploads — reports tab (two logos)
        if (tab === 'reports') {
            for (const slotId of ['report_left_logo', 'report_right_logo']) {
                const inp = document.getElementById(slotId + '_input');
                if (inp?.files[0]) payload[slotId + '_data'] = await fileToBase64(inp.files[0]);
                payload[slotId + '_cleared'] = document.getElementById(slotId + '_cleared')?.value || '0';
            }
        }

        // Sound upload — system tab
        if (tab === 'system' && pendingSoundFile) {
            payload['notification_sound_data'] = await fileToBase64(pendingSoundFile);
            payload['notification_sound_name']  = pendingSoundFile.name;
        }

        try {
            const res = await fetch('api/settings/save.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload),
            });
            const data = await res.json();
            if (data.success) {
                showToast('Settings saved successfully', 'success');
                document.body.classList.remove('dirty');
                if (tab === 'system') { pendingSoundFile = null; document.getElementById('notification_sound_cleared').value = '0'; }
                if (tab === 'reports') {
                    document.getElementById('report_left_logo_cleared').value  = '0';
                    document.getElementById('report_right_logo_cleared').value = '0';
                }
            } else {
                showToast(data.message || 'Failed to save settings', 'error');
            }
        } catch (err) {
            showToast('Network error — please try again', 'error');
        } finally {
            btn.disabled = false;
            btn.innerHTML = orig;
        }
    }

    // Drag-over for logo dropzone
    const dz = document.getElementById('logoDropzone');
    if (dz) {
        dz.addEventListener('dragover', e => { e.preventDefault(); dz.classList.add('drag-over'); });
        dz.addEventListener('dragleave', () => dz.classList.remove('drag-over'));
        dz.addEventListener('drop', e => {
            e.preventDefault(); dz.classList.remove('drag-over');
            const file = e.dataTransfer.files[0];
            if (file) { document.getElementById('logoInput').files = e.dataTransfer.files; handleLogoUpload(document.getElementById('logoInput')); }
        });
    }

    // ── Banner preview ───────────────────────────────────────────────────
    const bannerColors = {
        info:    'bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 border border-blue-200 dark:border-blue-800/30',
        warning: 'bg-yellow-50 dark:bg-yellow-900/20 text-yellow-700 dark:text-yellow-300 border border-yellow-200 dark:border-yellow-800/30',
        danger:  'bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-300 border border-red-200 dark:border-red-800/30',
    };
    const bannerIcons = { info: 'uil-info-circle', warning: 'uil-exclamation-triangle', danger: 'uil-exclamation-circle' };
    let currentBannerType = document.getElementById('dashboard_banner_type')?.value || 'info';

    document.getElementById('dashboard_banner')?.addEventListener('input', function () {
        const wrap = document.getElementById('bannerPreviewWrap');
        const text = document.getElementById('bannerPreviewText');
        if (this.value.trim()) { wrap.classList.remove('hidden'); text.textContent = this.value; }
        else { wrap.classList.add('hidden'); }
        document.body.classList.add('dirty');
    });

    function setBannerType(type) {
        currentBannerType = type;
        document.getElementById('dashboard_banner_type').value = type;
        document.querySelectorAll('.banner-pill').forEach(p => {
            p.className = 'banner-pill ' + (p.dataset.type === type ? `active-${type}` : '');
        });
        const preview = document.getElementById('bannerPreview');
        const icon    = document.getElementById('bannerPreviewIcon');
        if (preview) { preview.className = `rounded-xl px-4 py-3 flex items-center gap-3 text-sm font-medium ${bannerColors[type]}`; }
        if (icon) icon.className = `uil ${bannerIcons[type]} text-lg flex-shrink-0`;
        document.body.classList.add('dirty');
    }

    // ── Toggle switch ────────────────────────────────────────────────────
    function toggleSwitch(trackId, inputId) {
        const track = document.getElementById(trackId);
        const input = document.getElementById(inputId);
        const isOn  = track.classList.toggle('on');
        input.value = isOn ? '1' : '0';
        if (trackId === 'maintenanceToggle') {
            const lbl = document.getElementById('maintenanceLabel');
            lbl.textContent = isOn ? 'ON' : 'OFF';
            lbl.className = `text-xs font-semibold ${isOn ? 'text-red-500' : 'text-slate-400 dark:text-slate-500'}`;
        }
        document.body.classList.add('dirty');
    }

    // ── Notification sound ────────────────────────────────────────────────
    let pendingSoundFile = null;  // File object waiting to be uploaded on save
    let previewAudio = null;       // Audio instance used for test playback
    let testTimer = null;

    function handleSoundUpload(input) {
        const file = input.files[0];
        if (!file) return;
        const maxMB = 5;
        if (file.size > maxMB * 1024 * 1024) {
            showToast(`Audio file must be under ${maxMB}MB`, 'error');
            input.value = '';
            return;
        }
        pendingSoundFile = file;
        document.getElementById('soundFileName').textContent = file.name;
        document.getElementById('notification_sound_cleared').value = '0';

        // Build a local object URL for immediate test playback
        if (previewAudio) { previewAudio.pause(); previewAudio = null; }
        previewAudio = new Audio(URL.createObjectURL(file));

        document.body.classList.add('dirty');
        showToast('Sound file ready — click "Test Sound" to preview or save to apply.', 'success');
    }

    function clearSound() {
        pendingSoundFile = null;
        if (previewAudio) { previewAudio.pause(); previewAudio = null; }
        document.getElementById('soundInput').value = '';
        document.getElementById('soundFileName').textContent = 'Default alert sound (alert.mp3)';
        document.getElementById('notification_sound_cleared').value = '1';
        document.body.classList.add('dirty');
        showToast('Custom sound removed — default will be used.', 'success');
    }

    function testNotificationSound() {
        const volume   = parseInt(document.getElementById('notification_volume').value, 10) / 100;
        const duration = Math.max(1, Math.min(30, parseInt(document.getElementById('notification_duration').value, 10) || 3)) * 1000;

        // Resolve the audio source
        let src = null;
        if (pendingSoundFile) {
            src = URL.createObjectURL(pendingSoundFile);
        } else {
            // Use saved path or fallback default
            const savedPath = '<?= !empty($settings['notification_sound']) ? addslashes(s($settings, 'notification_sound')) : '' ?>';
            src = savedPath ? savedPath : '/assets/sounds/alert.mp3';
        }

        if (testTimer) { clearTimeout(testTimer); testTimer = null; }
        const audio = new Audio(src);
        audio.volume = volume;
        audio.play().catch(() => showToast('Browser blocked autoplay — interact with the page first.', 'error'));

        // Show waveform
        const wv = document.getElementById('soundWaveform');
        const st = document.getElementById('soundStatus');
        const tb = document.getElementById('testSoundBtn');
        wv.classList.remove('hidden');
        wv.classList.add('flex');
        st.classList.remove('hidden');
        tb.disabled = true;

        testTimer = setTimeout(() => {
            audio.pause();
            audio.currentTime = 0;
            wv.classList.add('hidden');
            wv.classList.remove('flex');
            st.classList.add('hidden');
            tb.disabled = false;
        }, duration);
    }

    // Sync volume slider gradient on input
    document.getElementById('notification_volume')?.addEventListener('input', function () {
        this.style.setProperty('--val', this.value + '%');
    });
    // Set initial gradient
    const volSlider = document.getElementById('notification_volume');
    if (volSlider) volSlider.style.setProperty('--val', volSlider.value + '%');

    // ── Save ─────────────────────────────────────────────────────────────
    async function saveTab(tab) {
        const btn = document.querySelector(`[onclick="saveTab('${tab}')"]`) ||
                    document.getElementById('globalSaveBtn');
        const orig = btn.innerHTML;
        btn.disabled = true;
        btn.innerHTML = `<i class="uil uil-spinner-alt animate-spin"></i> Saving…`;

        // Collect fields for each tab
        const fieldMaps = {
            barangay: ['barangay_name','barangay_address','barangay_contact','barangay_email'],
            reports:  ['report_signatory_name','report_signatory_pos','report_footer_note'],
            system:   ['force_resolve_hours','maintenance_mode','dashboard_banner','dashboard_banner_type',
                       'notification_volume','notification_duration','notification_sound_cleared'],
        };

        const payload = { tab };
        (fieldMaps[tab] || []).forEach(key => {
            const el = document.getElementById(key);
            if (el) payload[key] = el.value;
        });

        // Handle file uploads
        if (tab === 'barangay') {
            const logoFile = document.getElementById('logoInput')?.files[0];
            if (logoFile) payload['barangay_logo_data'] = await fileToBase64(logoFile);
        }
        if (tab === 'reports') {
            const sealFile = document.getElementById('sealInput')?.files[0];
            if (sealFile) payload['report_seal_data'] = await fileToBase64(sealFile);
        }
        if (tab === 'system' && pendingSoundFile) {
            payload['notification_sound_data'] = await fileToBase64(pendingSoundFile);
            payload['notification_sound_name']  = pendingSoundFile.name;
        }

        try {
            const res = await fetch('api/settings/save.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload),
            });
            const data = await res.json();
            if (data.success) {
                showToast('Settings saved successfully', 'success');
                document.body.classList.remove('dirty');
                if (tab === 'system') {
                    pendingSoundFile = null;
                    document.getElementById('notification_sound_cleared').value = '0';
                }
            } else {
                showToast(data.message || 'Failed to save settings', 'error');
            }
        } catch (err) {
            showToast('Network error — please try again', 'error');
        } finally {
            btn.disabled = false;
            btn.innerHTML = orig;
        }
    }

    function fileToBase64(file) {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = () => resolve(reader.result);
            reader.onerror = reject;
            reader.readAsDataURL(file);
        });
    }

    // Warn on unsaved changes
    window.addEventListener('beforeunload', e => {
        if (document.body.classList.contains('dirty')) {
            e.preventDefault();
            e.returnValue = '';
        }
    });
    </script>
</body>
</html>