<?php
// helpers/settings_helper.php
// Usage: $settings = SystemSettings::get();
//        $name     = SystemSettings::value('barangay_name', 'Barangay');

class SystemSettings
{
    private static ?array $cache = null;

    private static array $defaults = [
        'barangay_name'              => 'Barangay Gulod',
        'barangay_address'           => 'Novaliches, Quezon City',
        'barangay_contact'           => '',
        'barangay_email'             => '',
        'barangay_logo'              => '',
        // Report header
        'report_left_logo'           => '',
        'report_right_logo'          => '',
        'report_republic_line'       => 'REPUBLIC OF THE PHILIPPINES',
        'report_barangay_line'       => 'BARANGAY GULOD',
        'report_address_line'        => 'VILLAFLOR VILLAGE, DISTRICT V, QUEZON CITY',
        'report_tel_line'            => 'Tel. No. 8366-3198',
        // Officials
        'report_punong_name'         => 'REY ALDRIN S. TOLENTINO',
        'report_punong_position'     => 'Punong Barangay',
        'report_officials'           => '[]',
        'report_sk_name'             => 'ALJOHN JAYZEL E. CLEMENTE, JMA',
        'report_secretary_name'      => 'MILA B. NARIO',
        'report_treasurer_name'      => 'LUNINGNING R. ARATAS',
        // Signatory
        'report_signatory_name'      => '',
        'report_signatory_pos'       => 'Punong Barangay',
        'report_footer_note'         => 'This is an official document generated by the SafeChain Emergency Response System.',
        // System
        'force_resolve_hours'        => '6',
        'maintenance_mode'           => '0',
        'dashboard_banner'           => '',
        'dashboard_banner_type'      => 'info',
        // Notification sound
        'notification_sound'         => '',
        'notification_volume'        => '70',
        'notification_duration'      => '3',
    ];

    /**
     * Load all settings (with defaults for missing keys).
     */
    public static function get(): array
    {
        if (self::$cache !== null) return self::$cache;

        global $conn;
        $settings = self::$defaults;

        try {
            $result = $conn->query("SELECT setting_key, setting_value FROM system_settings");
            if ($result) {
                while ($row = $result->fetch_assoc()) {
                    $settings[$row['setting_key']] = $row['setting_value'];
                }
            }
        } catch (Exception $e) {
            // Table not yet created — return defaults silently
        }

        self::$cache = $settings;
        return $settings;
    }

    /**
     * Get a single setting value with optional fallback.
     */
    public static function value(string $key, string $fallback = ''): string
    {
        $settings = self::get();
        return $settings[$key] ?? $fallback;
    }

    /**
     * Is maintenance mode active?
     */
    public static function isMaintenanceMode(): bool
    {
        return self::value('maintenance_mode') === '1';
    }

    /**
     * How many hours before force-resolve is available?
     */
    public static function forceResolveHours(): int
    {
        return max(1, (int) self::value('force_resolve_hours', '6'));
    }

    /**
     * Full URL for barangay logo (or empty string).
     */
    public static function logoUrl(): string
    {
        $path = self::value('barangay_logo');
        if (empty($path)) return '';
        return rtrim(BASE_URL, '/') . '/' . ltrim($path, '/');
    }

    /**
     * Full URL for report seal (or empty string).
     */
    public static function sealUrl(): string
    {
        $path = self::value('report_seal');
        if (empty($path)) return '';
        return rtrim(BASE_URL, '/') . '/' . ltrim($path, '/');
    }

    /**
     * Full URL for the left report logo (QC logo).
     */
    public static function reportLeftLogoUrl(): string
    {
        $path = self::value('report_left_logo');
        if (empty($path)) return '';
        return rtrim(BASE_URL, '/') . '/' . ltrim($path, '/');
    }

    /**
     * Full URL for the right report logo (Barangay seal).
     */
    public static function reportRightLogoUrl(): string
    {
        $path = self::value('report_right_logo');
        if (empty($path)) return '';
        return rtrim(BASE_URL, '/') . '/' . ltrim($path, '/');
    }

    /**
     * Decoded kagawad/officials array.
     * Returns array of ['name' => ..., 'position' => ...]
     */
    public static function officials(): array
    {
        $raw = self::value('report_officials', '[]');
        $arr = json_decode($raw, true);
        return is_array($arr) ? $arr : [];
    }

    /**
     * Build the complete report header data as an associative array.
     * Use this in your report generation scripts.
     */
    public static function reportHeader(): array
    {
        $s = self::get();
        return [
            'left_logo_url'   => self::reportLeftLogoUrl(),
            'right_logo_url'  => self::reportRightLogoUrl(),
            'republic_line'   => $s['report_republic_line'],
            'barangay_line'   => $s['report_barangay_line'],
            'address_line'    => $s['report_address_line'],
            'tel_line'        => $s['report_tel_line'],
            'punong_name'     => $s['report_punong_name'],
            'punong_position' => $s['report_punong_position'],
            'officials'       => self::officials(),
            'sk_name'         => $s['report_sk_name'],
            'secretary_name'  => $s['report_secretary_name'],
            'treasurer_name'  => $s['report_treasurer_name'],
            'signatory_name'  => $s['report_signatory_name'],
            'signatory_pos'   => $s['report_signatory_pos'],
            'footer_note'     => $s['report_footer_note'],
        ];
    }
    public static function notificationSoundUrl(): string
    {
        $path = self::value('notification_sound');
        if (empty($path)) return '';
        return rtrim(BASE_URL, '/') . '/' . ltrim($path, '/');
    }

    /**
     * Notification volume as 0.0–1.0 float.
     */
    public static function notificationVolume(): float
    {
        return max(0, min(100, (int) self::value('notification_volume', '70'))) / 100;
    }

    /**
     * Notification play duration in milliseconds.
     */
    public static function notificationDurationMs(): int
    {
        return max(1, min(30, (int) self::value('notification_duration', '3'))) * 1000;
    }

    /**
     * Bust the in-memory cache (call after saving settings).
     */
    public static function clearCache(): void
    {
        self::$cache = null;
    }
}